a1 = Artist.create(name: "Michael Jackson", age: rand(50), title: "King of Pop")
a2 = Artist.create(name: "Stevie Wonder", age: rand(50), title: "Little Stevie Wonder")
a3 = Artist.create(name: "Elvis Presley", age: rand(50), title: "the King")
a4 = Artist.create(name: "Whitney Houston", age: rand(50), title: "The Voice")
a5 = Artist.create(name: "Beyoncé", age: rand(50), title: "Destiny's Child")

Instrument.create(name: "Guitar", classification: "Strings")
Instrument.create(name: "Violin", classification: "Strings")
Instrument.create(name: "Flute", classification: "Woodwind")
Instrument.create(name: "Xylophone", classification: "Percussion")

ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))
ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))
ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))
ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))
ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))
ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))
ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))
ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))
ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))
ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))
ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))
ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))
ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))
ArtistInstrument.create(artist_id: rand(5), instrument_id: rand(4))